spring:
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tale?serverTimezone=UTC&useSSL=false&characterEncoding=utf-8
    username: root
    password: root
#pagehelper
  #pagehelper.helper-dialect=mysql
  #pagehelper.reasonable=true
  #pagehelper.support-methods-arguments=true
  #pagehelper.page-size-zero=true
  #pagehelper.params=count=countSql

server:
  port: 8082
mybatis:
  mapper-locations: classpath:dao/*.xml
  type-aliases-package: com.blogsystem.entity
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  page-size-zero: true
  params: count=countSql

